export const ActionType = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
  ADD_TAG: 'ADD_TAG',
  REMOVE_TAG: 'REMOVE_TAG',
  SAVE_PROFILE: 'SAVE_PROFILE',
  SHOW_MODAL: 'SHOW_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SELECT_GIPHY: 'SELECT_GIPHY',
  CLEAR_GIPHY: 'CLEAR_GIPHY',
  REQUEST_EXCHANGE_RATES: 'REQUEST_EXCHANGE_RATES',
  POST_LIST: 'POST_LIST',
  POST_GET: 'POST_GET',
  POST_CREATE: 'POST_CREATE',
  POST_DELETE: 'POST_DELETE',
  POST_GET_COMMENTS: 'POST_GET_COMMENTS'
};
export default ActionType;
