export default {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
    ADD_TAG: 'ADD_TAG',
    REMOVE_TAG: 'REMOVE_TAG',
    SAVE_PROFILE: 'SAVE_PROFILE',
    SHOW_MODAL: 'SHOW_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL'
};
